name: Tag

on:
  push:
    branches: ["main"]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - run: npm i @semantic-release/git

      - name: Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
